<a href="https://colab.research.google.com/github/vicentcamison/idal_ia3/blob/main/3%20Aprendizaje%20profundo%20(II)/Sesion%202/cnn_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [2]:
input_1d = torch.randn(10, dtype=torch.float)
input_2d = torch.randn(2,5, dtype=torch.float)
input_2d_img = torch.randn(3, 10, 3, dtype=torch.float)

In [3]:
input_2d_img

tensor([[[ 1.1013, -0.7271, -0.6177],
         [ 0.0804, -1.4985,  0.9306],
         [ 0.9564, -0.2386,  0.3534],
         [ 1.0204,  0.8901,  2.1676],
         [-0.9275,  0.1841, -0.5260],
         [ 0.5356, -1.2847, -1.2048],
         [ 0.2553, -0.1102, -0.3894],
         [-0.2863, -1.9713, -2.3789],
         [-0.0111,  0.2147,  0.0078],
         [-0.1670,  0.6463, -0.4887]],

        [[-1.5745,  0.8593,  0.8954],
         [ 0.1955, -2.0928, -0.3917],
         [ 0.7534, -0.1216,  0.4532],
         [ 0.3213, -0.3882,  1.5452],
         [-0.7401, -0.1000,  1.3877],
         [-0.3390, -2.1040, -1.5613],
         [-0.9722, -0.6606,  1.7181],
         [-2.0132,  2.6791,  0.3635],
         [-0.5428, -0.5161,  0.1275],
         [ 1.2218,  0.6236, -0.5476]],

        [[ 0.7566,  0.1247,  1.0425],
         [-0.7307,  0.8789,  0.3867],
         [ 0.6304, -1.1177, -0.9068],
         [ 0.3806,  2.6149,  0.0783],
         [-2.5470, -0.3348, -0.8852],
         [ 0.7592, -0.2394,  0.9452],
        

In [4]:
## -- CONV 1D --

input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

In [5]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=2, stride=2, padding=1)

print('cnn1d_1: \n')
print(cnn1d_1(input_1d).shape, '\n')
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 5, 6]) 

tensor([[[-0.3864, -0.5798,  0.1700,  0.4329, -0.9241,  0.0122],
         [ 0.1748, -0.2820,  0.6160,  0.8441, -1.2547,  0.4512],
         [ 1.3394,  0.8850,  0.7408,  0.5006, -0.2718,  0.8240],
         [ 0.1200, -0.1060,  0.0440,  0.0243, -0.6411,  0.0325],
         [ 0.2847, -0.0896,  0.3512,  0.4053, -0.9405,  0.2865]]],
       grad_fn=<SqueezeBackward1>)


In [6]:
## -- CONV 1D A ENTRADAS 2D --
#También se puede aplicar la convolución 1D a tensores 2D
#lo preparamos primero añadiendo la capa de 'color'

input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [8]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)

print('cnn1d_5: \n')
print(cnn1d_5(input_2d).shape, '\n')
print(cnn1d_5(input_2d))

#En este caso, está cogiendo lo que normalmente identificamos como el EJE Y,
# como el número de canales de entrada (como si fueran dos colores distintos,
# o incluso interpretado como el resultado de dos filtros 'previos')

cnn1d_5: 

torch.Size([1, 1, 3]) 

tensor([[[ 0.2086, -0.3545, -0.7927]]], grad_fn=<SqueezeBackward1>)


In [9]:
cnn1d_6 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=2, stride=2, padding=1)

print('cnn1d_6: \n')
print(cnn1d_6(input_2d).shape, '\n')
print(cnn1d_6(input_2d))

cnn1d_6: 

torch.Size([1, 5, 3]) 

tensor([[[ 0.2728,  0.3686,  0.5055],
         [ 0.2795, -0.3451, -0.5035],
         [ 0.0066,  0.0158,  0.3461],
         [-0.2624, -0.9397, -0.4314],
         [ 0.1402,  0.5272, -0.0968]]], grad_fn=<SqueezeBackward1>)


In [12]:
## -- CONV 2D -- 

# Añadimos una nueva dimensión que (supongo) representa la cantidad
# de datos que tenemos (en este caso, sólo tenemos 1 imágen)

input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 10, 3])

In [13]:
# Creamos la capa convolucional
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, stride=1)

print('cnn2d_1: \n')
print(cnn2d_1(input_2d_img).shape, '\n')
print(cnn2d_1(input_2d_img))

cnn2d_1: 

torch.Size([1, 3, 8, 1]) 

tensor([[[[-0.5082],
          [-0.8444],
          [ 0.2749],
          [-0.1485],
          [ 0.1741],
          [ 1.2368],
          [ 0.4233],
          [-1.1538]],

         [[ 0.0338],
          [ 0.1162],
          [-0.0106],
          [-0.1152],
          [ 0.2214],
          [ 1.8717],
          [ 0.1294],
          [ 0.7271]],

         [[ 0.4780],
          [-0.1901],
          [ 1.1546],
          [-0.2633],
          [ 0.3349],
          [-0.7633],
          [ 0.3064],
          [ 1.4314]]]], grad_fn=<ThnnConv2DBackward>)


In [14]:
cnn2d_2 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=2, padding=1)

print('cnn2d_2 \n')
print(cnn2d_2(input_2d_img).shape, '\n')
print(cnn2d_2(input_2d_img))

cnn2d_2 

torch.Size([1, 5, 11, 4]) 

tensor([[[[-0.2944, -0.7804, -0.0280, -0.2256],
          [-0.8898, -0.2210,  0.4462, -0.4592],
          [-0.2321, -0.8641, -0.1671, -0.4519],
          [-0.2324, -0.7492, -0.7996, -0.8159],
          [-0.4311, -0.1112, -0.5630, -0.2854],
          [-0.3443, -0.4509,  0.3719,  0.0435],
          [-0.4565, -1.1000, -0.1061,  0.1430],
          [-0.6026, -0.6212,  0.9644,  0.7851],
          [-0.7568,  0.5040,  0.9238,  0.1894],
          [-0.4080, -0.2078, -0.3883, -0.1465],
          [ 0.0454, -0.0830, -0.4290, -0.2062]],

         [[ 0.3975,  0.8868, -0.1134,  0.0818],
          [ 0.3867, -0.1929,  0.5189,  0.5411],
          [ 0.2192,  1.2835, -0.8820,  0.1693],
          [ 0.1428,  0.7763,  0.9801,  1.0039],
          [ 0.0926,  0.1551, -0.8162,  0.4971],
          [ 0.3551,  0.7796,  0.1484,  0.7765],
          [ 0.3567,  0.9552, -0.0537, -0.9728],
          [ 0.5133, -0.0883, -1.0088, -0.0850],
          [ 0.6092, -0.0971,  0.9209,  0.3056],
