<a href="https://colab.research.google.com/github/vicentcamison/idal_ia3/blob/main/3%20Aprendizaje%20profundo%20(II)/Sesion%206/0_Test_LSTM_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

import tensorflow as tf

EJERCICIO: Crea una secuencia temporal (np.array) de 10 números reales (10 time steps). Crea
un modelo compuesto por una capa LSTM de 4 salidas conectada a una capa densa de 1
neurona. Evalúa la salida del modelo para la secuencia anterior en cada instante de tiempo. Nota:
recuerda que LSTM() requiere entradas tridimensionales, aunque tengamos sólo una secuencia.

*    Prueba a poner return_sequences=False. Observa la salida en ese caso.
*    Repite el ejercicio pero con un array de 10 time steps y 2 features.
*    Apila una segunda capa LSTM de 4 salidas tras la primera y antes de la capa densa. Recuerda
que la primera LSTM tiene que tener return_sequences=True. Observa la salida.

In [29]:
sequence = np.arange(0, 10, 1, dtype='float32')
# Ponemos dtype='float32' porque en caso contrario tira error

sequence = np.reshape(sequence, newshape=(1, -1, 1))

# las tres dimensiones de la entrada son (samples, time_steps, n_features)
# Se puede especificar la input_shape en la capa LSTM de forma input_shape=(time_steps, n_features)
model = Sequential()
model.add(LSTM(4, input_shape=(10, 1), return_sequences=True))
model.add(Dense(1))

y = model(sequence)
y

<tf.Tensor: shape=(1, 10, 1), dtype=float32, numpy=
array([[[ 0.        ],
        [-0.00340474],
        [ 0.01981339],
        [ 0.07457829],
        [ 0.13796529],
        [ 0.1901667 ],
        [ 0.22562914],
        [ 0.24615547],
        [ 0.25519532],
        [ 0.25592828]]], dtype=float32)>

Obtenemos un array de tamaño (1,10, 1) con los valores de la neuronafinal en cada paso (en este caso, están pasados por una dense monodimensional que lo condensa a un número por cada t a pesar de tener 4 células la LSTM y, por tanto, 4 pesos)

Si ahora hacemos **return_sequences = false**:

In [30]:
model_false = Sequential()
model_false.add(LSTM(4, input_shape=(10, 1), return_sequences=False))
model_false.add(Dense(1))

y = model_false(sequence)
y

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.15947077]], dtype=float32)>

Obtenemos únicamente el último valor

Repitiendo el ejercicio pero con un array de 10 time steps y 2 features:

In [33]:
sequence_2 = np.append(sequence, sequence, axis=2)

model2 = Sequential()
model2.add(LSTM(4, return_sequences=True))
model2.add(Dense(1))

model2_false = Sequential()
model2_false.add(LSTM(4, return_sequences=False))
model2_false.add(Dense(1))

y1 = model2(sequence_2)
y2 = model2_false(sequence_2)

print(y1,'\n\n', y2)

tf.Tensor(
[[[ 0.        ]
  [ 0.09082129]
  [ 0.1462333 ]
  [ 0.15326193]
  [ 0.14590923]
  [ 0.12960206]
  [ 0.10198941]
  [ 0.06646319]
  [ 0.02931612]
  [-0.00467111]]], shape=(1, 10, 1), dtype=float32) 

 tf.Tensor([[-0.02317992]], shape=(1, 1), dtype=float32)


Las shapes de las salidas son las mismas que con una única feature. Es decir, igual que en redes neuronales normales (dense, por ejemplo) el número de features no influye en la forma de la salida (obvio, pero es interesante verlo.

Aplicamos ahora una segunda capa LSTM de 4 salidas tras la primera y antes de la capa densa. Recuerda que la primera LSTM tiene que tener return_sequences=True. Observa la salida

In [35]:
model3 = Sequential()
model3.add(LSTM(4, return_sequences=True))
model3.add(LSTM(4))
model3.add(Dense(1))

y = model3(sequence)
y

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.2654268]], dtype=float32)>

Sólo se obtiene un único número. A pesar de que se le dice a la primera LSTM que return_sequences = True, estos resultados pasan a la segunda LSTM (que no tiene return_sequences=True) y se comprimen a un único resultado