<a href="https://colab.research.google.com/github/vicentcamison/idal_ia3/blob/main/3%20Aprendizaje%20profundo%20(II)/Sesion%201/01_PyTorch_Basico_Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![IDAL](https://i.imgur.com/tIKXIG1.jpg)  

#**Máster en Inteligencia Artificial Avanzada y Aplicada:  IA^3**
---


# PyTorch Basico Ejercicios 

En estos ejercicos crearemos algunos tensores y realizaremos operaciones básicos sobre ellos.


### 1. Realiza las importaciones standard
Importa torch and NumPy

In [ ]:
# TU CÓDIGO AQUÍ


### 2. Configura una semilla para los generadores de ambos Numpy y Pytorch con el valor "42"
Esto permite reproducir los mismos resultados "aleatorios"

In [ ]:
# TU CÓDIGO AQUÍ

### 3. Crea un NumPy array llamado "arr" que contenga 6 enteros aleatorios entre 0 (incluido) y 5 (excluido)

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

[3 4 2 4 4 1]


### 4. Crea a tensor "x" del array anterior 

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([3, 4, 2, 4, 4, 1])


### 5. Cambia el tipo de dato (`dtype`) de x de 'int32' a 'int64'
Nota: 'int64' tambien se puesde llamar 'LongTensor'

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

torch.LongTensor


### 6. Cambia la forma del tensor a un 3x2 tensor
Hay varias formas de hacer esto

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Retorna la columna de la derecha del tensor the right-hand column of tensor x

Atención a la forma de hacerlo. Hay varias posibilidades y cada una entrega los datos de forma diferente

In [ ]:
# # TU CÓDIGO AQUÍ

In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[4],
        [4],
        [1]])


In [ ]:
# TU CÓDIGO AQUÍ

In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([4, 4, 1])


### 8. Sin cambiar x, retorna un tensor con los valores cuadradaticos de x
Hay varias formas de hacer esto

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Crea un tensor "y" con el mismo número de elementos que x, de forma que pueda realizar una multoplicación de matrices.

Utiliza funciones de Pytorch directamente para crear un tensor de enteros aleatorios entre 0 (incluido) y 5 (excluido). 

Ten en cuenta qué forma debe tener para hacer la multiplicación de matrices...

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Realiza el producto de matrices entre x e y

In [ ]:
# TU CÓDIGO AQUÍ



In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Enhorabuena! Vamos calentando motores...

## Fin del Notebook

Referencias y modelos empleados para el Notebook: 

*   Documentación de [Pytorch](https://pytorch.org/docs/stable/index.html) 
*   [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi
*   [FastAI](https://www.fast.ai/) development notebooks by Jeremy Howard.
*   Documentación y cursos en [Pierian Data](https://www.pieriandata.com/)
